### ISSUE TITLE
Pipelines

### ISSUE THREAD

**Issue by nitrocode** [mszep/pandoc_resume#60]
Would be nice to have a github pipeline to build out the resume artifacts. I'm currently using the following for gitlab where my repo is hosted.

`.gitlab-ci.yml`
```
variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

image:
  name: docker/compose:1.22.0 # update tag to whatever version you want to use.
  entrypoint: ["/bin/sh", "-c"]

services:
  - docker:dind

before_script:
  - docker version
  - docker-compose version

build:
  stage: build
  script:
    - docker-compose up -d
  artifacts:
    paths:
      - output/ronak.pdf
      - output/ronak.html
      - output/*.log
```
