### ISSUE TITLE
dark mode toggle in html

### ISSUE THREAD

**Issue by nitrocode** [mszep/pandoc_resume#62]
Looks like it would be easy enough to add

https://darkmodejs.learn.uno/

**Comment by Albirew** [comment]
Since there's no picture, this very simple CSS should work:
```css
  @media (prefers-color-scheme: dark){
    html {
      filter: hue-rotate(180deg) invert(1);
      background-color:#333;
    }
  }
```
