### ISSUE TITLE
docker-compose up fails

### ISSUE THREAD

**Issue by kckeiks** [mszep/pandoc_resume#79]
### Expected Behavior

Creates pdf and html files in output directory

### Actual Behavior

```
resume-make    | make: *** No targets specified and no makefile found.  Stop.
resume-make exited with code 2
```
### Steps to reproduce the behavior

docker-compose up

### OS information
Ubuntu 20.04.2

**Comment by HarkuLi** [comment]
Encounter the same problem when I started docker container on Mac OS 11.5.2.

The error message is

```
resume-make    | make: *** No targets specified and no makefile found.  Stop.
resume-make exited with code 2
```

It seems that the `WORKDIR` of `pandoc/latex:2.9` image is `/data`. (See [Image Layer Details](https://hub.docker.com/layers/pandoc/latex/2.9.2.1/images/sha256-cc5f5c5aa1958766af7a1977085958ab5d36d59d2a870679a0c3a865cca293a6?context=explore))

However, the source code is mounted into the path `/home/app/resume`.

https://github.com/mszep/pandoc_resume/blob/dcdff60bcd60ab9d7b4ccf303c7c570777a0c95f/docker-compose.yml#L13

As a result, while the container is started and try to run `make` command in the `/data` path, there is no makefile found.

**Comment by jpduyx** [comment]
same issue here

**Comment by Spectrem12** [comment]
for windows, I had to change the yml file to this to get it to work..

```
version: '2'

services:

  resume-make:
    build:
      context: .
      dockerfile: ./.docker/resume.dockerfile
    command: make
    container_name: resume-make
    image: resume-make
    volumes:
      - "C:/your_path/pandoc_resume:/data"
```
